version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    reviewers:
      - "@octocat"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    groups:
      rails:
        patterns:
          - "rails*"
          - "activerecord*"
          - "actionpack*"
          - "activesupport*"
      testing:
        patterns:
          - "rspec*"
          - "factory_bot*"
          - "capybara*"
          - "selenium*"
      security:
        patterns:
          - "*security*"
          - "*audit*"
          - "brakeman*"

  - package-ecosystem: bundler
    directory: "/engines/immo_promo"
    schedule:
      interval: weekly
      day: "monday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps(engine)"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: "tuesday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(js)"
    groups:
      build-tools:
        patterns:
          - "bun*"
          - "webpack*"
          - "babel*"
          - "postcss*"
          - "tailwindcss*"
      frontend:
        patterns:
          - "@hotwired/*"
          - "@rails/*"
          - "alpinejs*"
          - "stimulus*"
      linting:
        patterns:
          - "eslint*"
          - "stylelint*"
          - "prettier*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "wednesday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: "thursday"
      time: "08:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "docker"
