default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: docusphere_development
  username: docusphere
  password: password
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: 5432

test:
  <<: *default
  database: docusphere_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: docusphere
  password: password
  host: <%= ENV.fetch("DATABASE_HOST", "db") %>
  port: 5432

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>