require 'bundler/setup'
require 'rake'
require 'rspec/core/rake_task'

APP_RAKEFILE = File.expand_path('../../Rakefile', __dir__)
load 'rails/tasks/engine.rake'

RSpec::Core::RakeTask.new(:spec)

task default: :spec
