name: Route Validation

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  route-validation:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: docusphere_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Set up Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install JavaScript dependencies
      run: bun install

    - name: Setup test database
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/docusphere_test
        REDIS_URL: redis://localhost:6379/1
      run: |
        bundle exec rails db:prepare

    - name: Run route audit
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/docusphere_test
        REDIS_URL: redis://localhost:6379/1
      run: |
        bundle exec rake routes:audit

    - name: Run route validation tests
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/docusphere_test
        REDIS_URL: redis://localhost:6379/1
      run: |
        bundle exec rspec spec/routing/ --format progress

    - name: Run navigation system tests
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/docusphere_test
        REDIS_URL: redis://localhost:6379/1
      run: |
        bundle exec rspec spec/system/navigation_paths_spec.rb --format progress

    - name: Generate route validation report
      if: failure()
      env:
        RAILS_ENV: test
        DATABASE_URL: postgres://postgres:password@localhost:5432/docusphere_test
        REDIS_URL: redis://localhost:6379/1
      run: |
        echo "## Route Validation Failures" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The following route issues were detected:" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        bundle exec rake routes:audit 2>&1 || true >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Please run \`rake routes:fix_common_issues\` to auto-fix ViewComponent issues." >> $GITHUB_STEP_SUMMARY